### ISSUE TITLE
mmd2PDF.pl complains about missing images

### ISSUE THREAD

**Issue by benzimmer** [fletcher/MultiMarkdown#12]
When running mmd2PDF.pl on my file it complains about not finding the images used in the document. HTML output is fine. Also if I run pdflatex manually on the created .tex file the pdf compiles just fine.
Perhaps its just me, but I have no possibility to test on another system.
If you need more info, please feel free to ask.

I'm on SnowLeopard with TexLive

**Comment by fletcher** [comment]
by default, MMD copies the following file extensions:  bib,pdf,png,gif,jpg

If you are relying on some other extension, you need to alter MultiMarkdown/Support.pm to copy these files as well.

If it's a common file extension, let me know and I can add it to the source as well.

If that's not the issue, I'll need more info and an example directory with the markdown file and the images that aren't being copied

**Comment by benzimmer** [comment]
images are in PNG format
i packed together the markdown file and images here:
http://dl.dropbox.com/u/314978/pmev.de-doku.zip

**Comment by fletcher** [comment]
the images have to be in same directory as the markdown document

**Comment by benzimmer** [comment]
aah, ok, didn't expect that. I'l stick with running pdflatex manually then.
