### ISSUE TITLE
Chapterstyle and pagestyle not set when using article.xslt

### ISSUE THREAD

**Issue by ghost** [fletcher/MultiMarkdown#13]
When article.xslt is selected, the chapterstyle and pagestyle metadata settings are ignored. 

Since the article.xslt uses the memoir class, as opposed to the LaTeX article class, it would be nice for the chapterstyle and pagestyle metadata settings to be honored—or at least the pagestyle setting so that the headers can be customized.

I plan to create a branch from the most recent commit, [f3f91b2](http://github.com/fletcher/MultiMarkdown/commit/f3f91b2e10a3025dd03e41a94b9475e9b80c66f7), and add the following two lines just after the `\begin{document}` line in article.xslt:

```
\chapterstyle{\mychapterstyle}
\pagestyle{\mypagestyle}
```

**Comment by cumulusware** [comment]
Commit [1d32a1c](http://github.com/cumulusware/MultiMarkdown/commit/1d32a1c7076ab527c2a3f07a3e2e8a7df3fedffe) fixes issue 13.
