### ISSUE TITLE
sffms.xslt uses underline instead of emph

### ISSUE THREAD

**Issue by ghost** [fletcher/MultiMarkdown#14]
The XSLT is using the `\underline` command instead of the recommended `\emph` command. The main issue with underline (which is the same in most LaTeX cases), is that it easily overfills the hbox, causing long emphasised passages to run off the edge of the page. Switching the XSLT to `\emph` sorted this right out. Proposed code:

```
<xsl:template match="html:em">
    <xsl:text>\emph{</xsl:text>
    <xsl:apply-templates select="node()"/>
    <xsl:text>}</xsl:text>
</xsl:template>
```

This will also keep emphasis semantic, since sffms can be toggled into non-submission mode, where italics are used as normal instead of underlining.

**Comment by fletcher** [comment]
Fixed.

Thanks for pointing this out.
