### ISSUE TITLE
Different Markup Syntaxes

### ISSUE THREAD

**Issue by Dahie** [fletcher/MultiMarkdown#15]
Ok, it's called MultiMarkDown and Markdown is great, but would it be feasible to configure additional syntax languages like textile? Some ideas issued in your ideas page are already possible with textile and wouldn't require you to build a large work around. Depending on the "complexity" of content the user could simply choose whether to use markdown as a simple and easy-to-read syntax or textile as one more-powerful, but also harder to learn. Just a thought. :)

**Comment by fletcher** [comment]
MMD and textile are two different syntaxes.  You are certainly welcome to use whichever is best suited to your needs, but I have no need for textile.
