### ISSUE TITLE
Update XSLTs to use 'glossaries' package, which has replaced 'glossary'

### ISSUE THREAD

**Issue by urschrei** [fletcher/MultiMarkdown#16]
It seems as if the standard 'glossary' package has now been replaced by the 'glossaries' package, which makes a number of changes to the way that entries are defined: http://www.latex-community.org/index.php?option=com_content&view=article&id=263%3Aglossaries-nomenclature-lists-of-symbols-and-acronyms&catid=55%3Alatex-general&Itemid=112

in particular, where \glossary{term}{definition} is used in the old package (and XSLT), the more complex 
\newglossaryentry{term}{name=term,description={definition}} seems to be mandated. It can then be referenced using \gls{term} (or variations).

I've had a look at the xhtml2latex XSLT, but altering it is beyond my capabilities...

**Comment by fletcher** [comment]
I'll try and take a look at this some time, but I'm not sure if I will get around to fixing this until it becomes an issue for me, to be honest.  I don't want to lead anyone on that I will fix this in the near future if I'm not certain I will get to it.

I'll definitely leave it as an open issue, and I am willing to take code submissions from anyone who fixes it.

**Comment by urschrei** [comment]
http://gist.github.com/470140
http://gist.github.com/470130

Preliminary attempts at transforming 
`[^footnote]: glossary: item`  
`item description`

into a properly formatted  
`\newglossaryentry{item}{name=item,description=item description}} \glsadd{name}`

I've used substring functions to extract and clean the entry name, above, and am using \glsadd{name} instead of \gls{name}, to avoid having to walk back up the tree and move/transform the original word. This means that the initial definition doesn't have a hyperlink to the glossary entry (though the glossary entry does have a link to the page).

I haven't looked at the sort functionality at all, yet.

(apologies for possible bad XSLT form)

**Comment by urschrei** [comment]
closing, as now a duplicate.
