### ISSUE TITLE
Add support for table cell wrapping to table_cleanup.pl

### ISSUE THREAD

**Issue by mehaase** [fletcher/MultiMarkdown#17]
I noticed in the google group that it is possible to wrap table cells when converting MMD to PDF if you add a "+" symbol to the end of the column format string. But the table_cleanup.pl script unhelpfully removes this plus symbol. I have a patch to fix this behavior.

**Comment by mehaase** [comment]
I pushed my patch to mehaase/MultiMarkdown.

**Comment by fletcher** [comment]
Can you send me a pull request for that?  Or is there a quick way for me merge your changes on github without a pull request?

**Comment by fletcher** [comment]
Never mind - found the fork queue

**Comment by fletcher** [comment]
Applied
