### ISSUE TITLE
Markdown Inside HTML Blocks

### ISSUE THREAD

**Issue by adamsmd** [fletcher/MultiMarkdown#18]
When doing a complex page sometimes I want to wrap a "<div class=blah>" around a piece of multimarkdown.  AFAICT, there is no way to do this in multimarkdown since the insides of block-level html elements are not formatted and there is no multimarkdown syntax for "div".

Could you add support for formatting multimarkdown inside bock-level elements?  For example, something like what markdown extra does http://michelf.com/projects/php-markdown/extra/#markdown-attr (I'm not attached to their particular rules).

**Comment by dgreen** [comment]
I believe this syntax is already supported.

**Comment by adamsmd** [comment]
You are right.  I was forgetting to add the "markdown=1" attribute.

Now marking this issue as closed.
