### ISSUE TITLE
HTML comments followed by text deleted in mmd2Latex

### ISSUE THREAD

**Issue by neilernst** [fletcher/MultiMarkdown#21]
Given the source code below in Scrivener:
    Some text....

```
<!-- 
\begin{table}[h]
\caption{Swanson's dimensions of maintenance}
\centering
\label{tbl:swanson}
\begin{tabular}{c|c}
[body of table]
\end{tabular}
\end{table} 
-->
We can shorten this table to identify the cause of change as either a) the system 
wasn’t       implemented properly; b) some assumption was incorrect; 
c) let’s improve the system.
```

That is, for a Latex table surrounded by HTML comments (to escape the Latex code), the mmd2latex.pl script will eat the text immediately following the close comment until it reaches a higher level heading.  Doesn't happen with the raw MMD file nor the HTML parser.

Workaround is to insert a blank line between the two. Hard to track down.

**Comment by fletcher** [comment]
I believe I fixed this by inserting a space after the comment.  Due to some limitations of XSLT, there's sort of a "lesser of two evils" choice to make, so IIRC this will have other limitations because of a forced newline after the comment.  but at least text won't disappear.
