### ISSUE TITLE
emacs tables

### ISSUE THREAD

**Issue by parjanya** [fletcher/MultiMarkdown#26]
Hi! First, let me thank you for this : ). It works really well, and it's a _lot_ faster than Pandoc.

Editing tables by hand is a pain; I've learnt to use some of Emacs just to help with that. I guess Emacs tables should be parsed as well... as there is no other good text-only table editor around.

**Comment by fletcher** [comment]
You are of course welcome to use whatever editor you like to compose MMD documents, but I won't be tailoring the syntax to accomodate everyone's editor choice.

If a true cross-platform, cross-editor standard table syntax every arises, then I would of course consider changing things.
