### ISSUE TITLE
Another problem with (Zotero-)BibTeX-keys

### ISSUE THREAD

**Issue by wadoli** [fletcher/MultiMarkdown#28]
Hi, thank you for the very fast comments on the other issues.

I have one more. This file:
    Title: 
    BibTeX: lit.bib
    Copyright: 
    Keywords: 
    Format: complete
    LaTeX XSLT: latex-snippet.xslt
    Address: Foobar
    Author: John Doe
    Base Header Level: 3
    Affiliation: University Schmersity
    Email: john.doe@uni.com
    Language: german
    Phone: 
    Subtitle: 
    Web: 
    Format: complete

```
# Einleitung #

Welsch räumt in seinem Aufsatz auch eventuelle Einwände
gegen das Konzept, das eine Uniformierung erbringen könnte,
ein. Er geht darauf ein, dass die Vielheit in Form von
Einzelkulturen verschwinden wird.[^fn24] Ein neuer Typus von
Vielheit von Kulturen und Lebensformen würde in
transkulturellen Kombinationen entstehen.[^fn25]



[^fn23]: [71–79][#welsch_transkulturalitat._1997].

[^fn24]: [77][#welsch_transkulturalitat._1997] oder nur als
simulierte Eigenheit, in Form von Folklore vorkommen werden
[72][#welsch_transkulturalitat._1997].

[^fn25]: [78–79][#welsch_transkulturalitat._1997].
```

produces the following error, when run through mmd2LaTeX.pl:
    -:42: parser error : Unescaped '<' not allowed in attributes values
    d="fn:fn24"><p><span class="externalcitation"> (<a id="welsch_transkulturalitat.
                                                                                   ^
    -:42: parser error : attributes construct error
    d="fn:fn24"><p><span class="externalcitation"> (<a id="welsch_transkulturalitat.
                                                                                   ^
    -:42: parser error : Couldn't find end of Start Tag a line 42
    d="fn:fn24"><p><span class="externalcitation"> (<a id="welsch_transkulturalitat.
                                                                                   ^
    -:42: parser error : Opening and ending tag mismatch: em line 42 and a
    (<a id="welsch_transkulturalitat.<em>1997">welsch_transkulturalitat.<em>1997</a>
                                                                                   ^
    -:42: parser error : Opening and ending tag mismatch: em line 42 and span
    ">welsch_transkulturalitat.<em>1997</a>, <span class="locator">77</span>)</span>
                                                                                   ^
    -:44: parser error : Unescaped '<' not allowed in attributes values
    <span class="externalcitation"> (<a id="welsch</em>transkulturalitat._1997">wels
                                                  ^
    -:44: parser error : attributes construct error
    <span class="externalcitation"> (<a id="welsch</em>transkulturalitat._1997">wels
                                                  ^
    -:44: parser error : Couldn't find end of Start Tag a line 44
    <span class="externalcitation"> (<a id="welsch</em>transkulturalitat._1997">wels
                                                  ^
    -:44: parser error : Opening and ending tag mismatch: span line 44 and em
    <span class="externalcitation"> (<a id="welsch</em>transkulturalitat._1997">wels
                                                       ^
    -:44: parser error : Opening and ending tag mismatch: span line 42 and em
    lass="externalcitation"> (<a id="welsch</em>transkulturalitat._1997">welsch</em>
                                                                                   ^
    -:44: parser error : Opening and ending tag mismatch: p line 42 and a
    a id="welsch</em>transkulturalitat._1997">welsch</em>transkulturalitat._1997</a>
                                                                                   ^
    -:44: parser error : Opening and ending tag mismatch: li line 42 and span
    >welsch</em>transkulturalitat._1997</a>, <span class="locator">72</span>)</span>
                                                                                   ^
    -:44: parser error : Opening and ending tag mismatch: ol line 40 and p
    ef:fn24" title="return to article" class="reversefootnote">&#160;&#8617;</a></p>
                                                                                   ^
    -:44: parser error : Opening and ending tag mismatch: div line 38 and li
    n24" title="return to article" class="reversefootnote">&#160;&#8617;</a></p></li
                                                                                   ^
    -:48: parser error : Opening and ending tag mismatch: body line 10 and ol
    </ol>
         ^
    -:49: parser error : Opening and ending tag mismatch: html line 5 and div
    </div>
          ^
    -:50: parser error : Extra content at the end of the document
    </body>
    ^
    unable to parse -
Oddly enough, other references to this item worked flawlessly throughout a larger file.

**Comment by fletcher** [comment]
This is the same issue - remove underscore characters from citation keys and it should be fine.
