### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by kylef** [fletcher/MultiMarkdown#29]
What are the dependencies for MultiMarkdown? I get a load of command not found. I am guessing this needs pdfTeX, which needs tex. But that only builds 32-bit and needs a lot of patches. Anything else before I try and get this built? Will it work with MacTeX?

```
sh: pdflatex: command not found
sh: bibtex: command not found
sh: makeindex: command not found
sh: kpsewhich: command not found
sh: makeindex: command not found
sh: pdflatex: command not found
sh: pdflatex: command not found
sh: pdflatex: command not found
sh: pdflatex: command not found
```

**Comment by fletcher** [comment]
MMD 2.0 (which you are referring to) doesn't technically have any dependencies.

If you want to process a LaTeX file into a PDF, then yes, you do of course need a working LaTeX installation.  I use MacTeX.

F-
