### ISSUE TITLE
Referring to the same footnote N times in a document prints it N consecutive times in the footnotes section

### ISSUE THREAD

**Issue by dandv** [fletcher/MultiMarkdown#3]
Test case also at [Babelmark](http://babelmark.bobtfish.net/?markdown=For+most+cases[^fn1]%2C+the+procedure+will+produce+sensible+results.%0D%0A%0D%0A[...+later+in+the+document+...]%0D%0A%0D%0AIn+a+few+particular+cases[^fn1]%2C+one+should...%0D%0A%0D%0A[...+more+of+the+document+follows...+]%0D%0A%0D%0AWe+have+achieved+satisfactory+results+for+the+general+situation[^fn1].%0D%0A%0D%0A%23%23+Footnotes%0D%0A%0D%0A[^fn1]%3A+there+are+a+few+exceptions%3A+...):

```
For most cases[^fn1], the procedure will produce sensible results.

[... later in the document ...]

In a few particular cases[^fn1], one should...

[... more of the document follows... ]

We have achieved satisfactory results for the general situation[^fn1].

## Footnotes

[^fn1]: there are a few exceptions: foos, bars, and bazes.
```

will produce the footnote repeated 3 times in the same location:

```
<p>For most cases<a href="#fn:fn1" id="fnref:fn1" class="footnote">1</a>, the procedure will produce sensible results.</p>

<p>[... later in the document ...]</p>

<p>In a few particular cases<a href="#fn:fn1" id="fnref:fn1" class="footnote">2</a>, one should...</p>

<p>[... more of the document follows... ]</p>

<p>We have achieved satisfactory results for the general situation<a href="#fn:fn1" id="fnref:fn1" class="footnote">3</a>.</p>

<h2 id="footnotes">Footnotes</h2>

<div class="footnotes">
<hr />
<ol>

<li id="fn:fn1"><p>there are a few exceptions: ...<a href="#fnref:fn1" class="reversefootnote">&#160;&#8617;</a></p></li>

<li id="fn:fn1"><p>there are a few exceptions: ...<a href="#fnref:fn1" class="reversefootnote">&#160;&#8617;</a></p></li>

<li id="fn:fn1"><p>there are a few exceptions: ...<a href="#fnref:fn1" class="reversefootnote">&#160;&#8617;</a></p></li>

</ol>
</div>
```

IMO, there should be only one occurrence of the footnote, preceded by backlinks to its references throughout the document. MediaWiki does [just that](http://en.wikipedia.org/wiki/Physics#cite_note-Feynman_lectures-6).

**Comment by fletcher** [comment]
For those new to the thread, this has been discussed previously between Dan and I:

http://groups.google.com/group/multimarkdown/browse_thread/thread/e714c49b5b6ab661

I'm leaving the issue open for further comments.

**Comment by fletcher** [comment]
Closing the issue.  If anyone has further comments to make, please feel free to reopen it, or open a new one.
