### ISSUE TITLE
support for subscript/superscript

### ISSUE THREAD

**Issue by munhitsu** [fletcher/MultiMarkdown#34]
Would it be possible to add support for sub/super script?
It could borrow the syntax from pandoc:

```
H~2~O is a liquid.  2^10^ is 1024.
```

see: http://johnmacfarlane.net/pandoc/README.html#superscripts-and-subscripts

**Comment by fletcher** [comment]
For now you can use the math syntax to do this, e.g.:

\[ x^2 \]

F-

On Jul 27, 2011, at 1:50 PM, munhitsu wrote:

> Would it be possible to add support for sub/super script?
> It could borrow the syntax from pandoc:
> 
>    H~2~O is a liquid.  2^10^ is 1024.
> 
> see: http://johnmacfarlane.net/pandoc/README.html#superscripts-and-subscripts
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fletcher/MultiMarkdown/issues/34

## 

Fletcher T. Penney
fletcher@fletcherpenney.net
