### ISSUE TITLE
Citations treated as footnotes in 3.1b1

### ISSUE THREAD

**Issue by dphenderson** [fletcher/MultiMarkdown#35]
Using multimarkdown on Mac OS X lion compiled via homebrew, version 3.1b1 treats citations like footnotes.

**Comment by fletcher** [comment]
Not sure exactly what you mean. Are you exporting to LaTeX? HTML
doesn't have citations, so everything is a footnote.

F

Sent from my iPhone

On Sep 15, 2011, at 3:04 PM, dphenderson
reply@reply.github.com
wrote:

**Comment by dphenderson** [comment]
Okay, then the behavior documented in the mmd manual is incorrect that is what I was expecting. I realize that HTML doesn't have semantic support for citations. I'll modify the output to suit my needs. Thanks for a great tool, it's part of my daily workflow.

**Comment by fletcher** [comment]
The manual is in need of some updating (it's a wiki so anyone can help....  Wink, wink....  ;)
