### ISSUE TITLE
cat not a recognized command in Windows

### ISSUE THREAD

**Issue by drolander** [fletcher/MultiMarkdown#4]
The mmd scripts don't work on Windows due to cat not being a recognized command in Windows. This line:

```
unless (my $return = eval `cat "$file"`) {
```

causes this error:

```
'cat' is not recognized as an internal or external command,
operable program or batch file.
couldn't do C:/Program Files/MultiMarkdown/bin/MultiMarkdown/Support.pm:  
at C:\Program Files\MultiMarkdown\bin\mmd2XHTML.pl line 153.
couldn't run C:/Program Files/MultiMarkdown/bin/MultiMarkdown/Support.pm 
at C:\Program Files\MultiMarkdown\bin\mmd2XHTML.pl line 154.
```

**Comment by drolander** [comment]
In looking over the mmd2XHTML.pl script, it looks to me like the real issue is that on Windows you are attempting to load Support.pm twice, once using the Windows method and again using the Unix/Mac method. I think the if block starting at line 135:

```
if ($MMDPath eq "") {
    die "You do not appear to have MultiMarkdown installed.\n";
} else {
    # Load the MultiMarkdown::Support.pm module
    $MMDPath = abs_path($MMDPath);
    LoadModule("$MMDPath/bin/MultiMarkdown/Support.pm");
}
```

should really be inside the else block that starts at line 107 (the section labeled # We're running Mac OS X or some *nix), and in fact when I move that section of code everything works fine on Windows.

I haven't tested the other scripts yet.

**Comment by fletcher** [comment]
This should be fixed now (9/3/09)  - I removed the "cat" section when running on Windows.  This could make the system vulnerable to other errors when unable to find the Support file.  But for now it's ok.
