### ISSUE TITLE
table_cleanup.pl produces unbalanced columns if >ASCII characters

### ISSUE THREAD

**Issue by elmimmo** [fletcher/MultiMarkdown#40]
The script to clean-up tables does not seem to correctly count the number of characters in lines with accented characters, such as this:

```
| Año | Facturación |  
| ---- | -----------: |  
| 2011 |     3.000€ |  
| 2012 |    15.000€ |  
```

**Comment by fletcher** [comment]
Yup.

It's been a while since I looked (I don't use this script anymore since developing Composer), but I did not see a straightforward fix to this.

I welcome proposed solutions.  But I'm not actively developing this script right now.

**Comment by elmimmo** [comment]
I proposed one at https://github.com/fletcher/MMD-Support/issues/2, as that seems the proper place for the latest version.
