### ISSUE TITLE
Inline footnotes and line breaks

### ISSUE THREAD

**Issue by memeplex** [fletcher/MultiMarkdown#42]
I'm not sure if this is a bug or it's by design, but inline footnotes are not taken to be footnotes when there is a hard linebreak in the text. For example:

```
some text [^this is a footnote]

more text [^this is
not]
```

It's advised in the syntax guide to experiment with the footnote syntax and report border cases, so I'm doing that here.

**Comment by fletcher** [comment]
It's on purpose, though I'm considering allowing one newline, but not two.   In other words, inline footnotes must be a single paragraph.

**Comment by fletcher** [comment]
I changed this to allow line breaks, but not paragraph breaks inside inline footnotes.

As an aside, you opened this issue in the old perl MMD project, rather than MMD-4.  I didn't notice during my first reply, but wanted to clarify for any future issues.

F-
