### ISSUE TITLE
Syntax Guide table example error

### ISSUE THREAD

**Issue by jgclark** [fletcher/MultiMarkdown#43]
The main example table in https://github.com/fletcher/MultiMarkdown/wiki/MultiMarkdown-Syntax-Guide doesn't render properly.

**Comment by fletcher** [comment]
You know that github's wiki's don't support MultiMarkdown, right?  This site is set up to edit the source --- none of it renders properly.

**Comment by jgclark** [comment]
I hadn't made that connection, no.  I don't think it would hurt to put a note at the start of the file to say that the file doesn't render fully in some settings, particularly here in git which is the first time it might be viewed.

**Comment by fletcher** [comment]
The wiki is actually outdated.  This is the old perl version of MultiMarkdown (v2).  The current version is v4 (https://github.com/fletcher/MultiMarkdown-4).  It has up to date documentation.

I don't anticipate updating this wiki.
