### ISSUE TITLE
specify metadata at CLI

### ISSUE THREAD

**Issue by wfalkwallace** [fletcher/MultiMarkdown#46]
I'd love to be able to specify metadata (like css) on the command line, rather than in the doc.

**Comment by fletcher** [comment]
You can already.  Simply prepend the metadata before the file contents (in a separate file, or via a the "echo" command, for example).  That's the beauty of command line programs -- they allow you to do so much by chaining other programs.  For example:

```
cat meta.txt file.txt | multimarkdown > file.html
```

This allows you to reuse metadata across documents easily.

**Comment by wfalkwallace** [comment]
ahh, good call. sorry I didn't think of this. Thanks for the tip.

**Comment by fletcher** [comment]
Let me know if you have trouble with this.
