### ISSUE TITLE
blockquote syntax is ignored in the cells

### ISSUE THREAD

**Issue by Oleksiy-Yakovenko** [fletcher/MultiMarkdown#48]
Hello.

According to multimarkdown documentation: 

`You can use normal Markdown markup within the table cells.`

but when i try this:

```
|col1 |col2 |
|:---|:---|
|>hello|blockquote|
```

i get this output (`>` is converted to `&gt;`):

| col1 | col2 |
| :-- | :-- |
| >hello | blockquote |

(github does the same as multimarkdown)

is there any other way to indent content in table cells, or any chance this issue will get fixed?

**Comment by fletcher** [comment]
Blockquotes are block level elements.  They can't be used inside span level elements like a table cell.

F

**Comment by Oleksiy-Yakovenko** [comment]
Are you absolutely sure about that? Even paragraphs and divs are valid inside table cells, why not blockquote? Google chrome displays them fine in table cells, and I believe it's perfectly valid at least with HTML5.

I cannot find any rules in the [HTML5 spec](http://www.w3.org/TR/html5/dom.html#flow-content) which forbid embedding <blockquote> inside of <td>.

On the unofficial side of things, there's [the table](http://www.cs.tut.fi/~jkorpela/html/nesting.html) showing which elements can be nested, and td clearly is allowed to nest content-flow elements, which blockquote is one of.

**Comment by fletcher** [comment]
#resolve

Blockquotes are block level elements.  They can't be used inside span 
level elements like a table cell.

Fletcher

On 6/23/14, 12:26 PM, Alexey Yakovenko wrote:

> Hello.
> 
> According to multimarkdown documentation:
> 
> |You can use normal Markdown markup within the table cells.|
> 
> but when i try this:
> 
> ||col1 |col2 |
> |:---|:---|
> |>hello|blockquote|
> |
> 
> i get this output (|>| is converted to |&gt;|):
> 
> _/Property:/_     _/Function:/_
> 
> > hello   blockquote
> 
> (github does the same as multimarkdown)
> 
> is there any other way to indent content in table cells, or any chance
> this issue will get fixed?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fletcher/MultiMarkdown/issues/48.

## 

Fletcher T. Penney
fletcher@fletcherpenney.net

**Comment by Oleksiy-Yakovenko** [comment]
| col1 | col2 |
| :-- | :-- |
| <blockquote>Thanks for replying and the nice attitude.</blockquote> | And have a nice day |

**Comment by fletcher** [comment]
Markdown blocks, not HTML blocks. 

F

**Comment by fletcher** [comment]
Looks like one of my comments that was delayed and presumed lost was subsequently accepted, hence the repetition...

Anyways, since things seem to be out of order above, to clarify.  I understand that HTML allows almost anything inside a table cell, but Markdown (and therefore MultiMarkdown) does not.

F-

**Comment by Oleksiy-Yakovenko** [comment]
Yeah, I understood that after your previous post. Thanks for clarification. Although it's strange that you can't change that, since original markdown has neither tables, nor formal standard.

**Comment by fletcher** [comment]
Markdown does specify a distinction between block level and span level elements.  I'm sure if you think it through, you'll realize why allowing block level elements inside a table cell won't work within MultiMarkdown.  If you want complicated tables, you'll need to hand code them. 

http://daringfireball.net/projects/markdown/syntax

**Comment by Oleksiy-Yakovenko** [comment]
I'll just tell the users to use <blockquote> tag directly -- it works in multimarkdown tables.
Just hoped it might be easy to get ">" syntax working.

**Comment by fletcher** [comment]
Not if they use multiline block quotes it won't....

**Comment by Oleksiy-Yakovenko** [comment]
Single-line is good enough for our use case
