### ISSUE TITLE
Rowspanning support for tables

### ISSUE THREAD

**Issue by HLFH** [fletcher/MultiMarkdown#49]
Could you support rowspanning for tables ?

**Comment by fletcher** [comment]
1) This version of MMD is obsolete (by 3-4 years).  No further development is happening here.  See MMD-4 https://github.com/fletcher/MultiMarkdown-4

2) If there's a good syntax for rowspanning, I'm happy to support it.  Be warned, however, that in the years that I have had that offer on the table, no one has been able to suggest a good syntax.  ;)
