### ISSUE TITLE
MultiMarkdown appears to have issue with TexLive2008

### ISSUE THREAD

**Issue by dgreen** [fletcher/MultiMarkdown#5]
Trying to use `mmd2PDFXeLaTeX.pl basic.mmd` causes a stop for input inside xelatex (or latex if the other script is used.

```
 (/usr/local/texlive/2008/texmf/tex/latex/config/color.cfg))
 ! Missing \endcsname inserted.
```

Here is a small `basic.mmd`

```
 Title: Test 
 Author: David Green  
 Date: 07 September 2009  
 Format: complete  
 LaTex xslt: article  
 Base Header Level: 2  

 Task - Model a Digital Logic
 ============================

 The purpose of this program is to model some simple digital logic --
 a register and a counter.
```

**Comment by fletcher** [comment]
Works fine for me with TeXLive 2007 or 2008 - perhaps you have something else going on with your installation?

**Comment by fletcher** [comment]
Has anyone else seen this??

**Comment by dgreen** [comment]
I thought I replied to you that I resolved the issue.  It was interference of an LyX install of a few classes and the TexLive classes.

**Comment by fletcher** [comment]
I must have missed that reply - glad that the problem was solved for you!
