### ISSUE TITLE
RTL?

### ISSUE THREAD

**Issue by mzaini30** [fletcher/MultiMarkdown#51]
Can I write rtl direction in MultiMarkdown? (Ex: for writing arabic letter)
Thanks :)

**Comment by fletcher** [comment]
Thanks for stopping by.

1) This is the perl version of MMD which has been obsolete for years.  The current version is MMD-4:

```
<https://github.com/fletcher/MultiMarkdown-4/>
```

2) MMD does not offer specific features related to RTL languages, but your best bet for information is the discussion list.  You'll be able to get more helpful information there from other users of RTL languages:

```
<https://groups.google.com/forum/#!forum/multimarkdown>
```
