### ISSUE TITLE
Editor Based on MultiMarkDown

### ISSUE THREAD

**Issue by RoyiAvital** [fletcher/MultiMarkdown#52]
Hello,
Is there an editor with live preview (Something like StackEdit just Offline) which is based on MultiMarkDown and has all the features (Math + PDF Export)?

Thank You.

**Comment by fletcher** [comment]
MultiMarkdown Composer

http://multimarkdown.com/

Created by yours truly.

**Comment by RoyiAvital** [comment]
I see...
Looks great.

Any chance for a Windows Portable version?

Thank You.

**Comment by fletcher** [comment]
Not likely.  Core engine is in C, but everything else is Obj-C based on OS X.

Anything other than very stripped down version would require a lot of work.
