### ISSUE TITLE
How to specify table of contents

### ISSUE THREAD

**Issue by davisford** [fletcher/MultiMarkdown#53]
Bitbucket markdown will auto-generate with `[TOC]`, but that doesn't work here.  You mentioned something in the docs about using an XSLT to create it, but can you provide an example of the xslt and usage?

**Comment by fletcher** [comment]
`{{TOC}}`, supported in 4.7 and up:

http://fletcher.github.io/MultiMarkdown-4/MMD_Users_Guide.html#4.7

**Comment by fletcher** [comment]
Oops -- didn't notice that this issue was posted to the very old MMD v2 project.  This is no longer maintained and doesn't support the `{{TOC}}` feature.

**Comment by davisford** [comment]
Yup, my fault @fletcher -- after I posted this, I realized this project was dead.  I was using the newer multimarkdown-4 and found the docs for that and discovered the `{{TOC}}`
