### ISSUE TITLE
Exclude some metadata in html head

### ISSUE THREAD

**Issue by feekApp** [fletcher/MultiMarkdown#54]
Hi,

I was wondering if there is a way to exclude some metadata items in the final rendered HTML.

For example I use the metadata transcludebase in order to incorporate my specific headers and footers.

So

``` markdown
transcludebase:   /Users/MyName/Dropbox/Sync/mmdStyles
```

renders:

``` html
<head>
    ...
    <meta name="transcludebase" content="/Users/MyName/Dropbox/Sync/mmdStyles"/>
    ...
</head>
```

But I do not want this metadata gets in the header. Is there a way to prevent this (not relevant information=> local and personal information)?

For example via

``` bash
multimarkdown --exclude-in-header='transcludebase,other-meta'  changelog.md
```

regards,
Feek

**Comment by fletcher** [comment]
This project has not been under active develop for many years.  Perhaps you were looking for this instead:

https://github.com/fletcher/MultiMarkdown-5

(Short answer is there is not a feature like that, but the source can be modified to exclude additional "standard" metadata keys.)
