### ISSUE TITLE
Multiple CSS files are not working anymore

### ISSUE THREAD

**Issue by supermueller** [fletcher/MultiMarkdown#56]
After updating MultiMarkdown to version 6.2.2 it is not possible anymore to include more than one CSS file to the header.

Before updating the MultiMarkdown code …

```
CSS:     css/styles-1.css
CSS:     css/styles-2.css
```
… was rendered to the following HTML code:

```
<head>
	<link type="text/css" rel="stylesheet" href=" css/styles-1.css"
	<link type="text/css" rel="stylesheet" href=" css/styles-2.css"
</head>
```

Version 6.2.2 now only renders the first line, all the following will be ignored.

By the way, the `HTML header: ` statement also only renders once.

**Comment by fletcher** [comment]
Correct.  Only one instance of each type of metadata is used.

You can either create a single CSS file that calls your other files, or you can use the HTML Header metadata to include whatever you like, including multiple `<link...` instances.

**Comment by supermueller** [comment]
… but the new version of MultiMarkdown also accept one `HTML header` statement, so the code will be rendered in a single line in the HTML code. This looks really ugly.

Do you have plans to bring back the ability to use more than one CSS or header statement?

**Comment by fletcher** [comment]
> … but the new version of MultiMarkdown also accept one HTML header statement, so the code will be rendered in a single line in the HTML code. This looks really ugly.

But it works, correct?

> Do you have plans to bring back the ability to use more than one CSS or header statement?

No.  That was only intended to be used for the `latex input` metadata, since it needed to be used more than once.

**Comment by supermueller** [comment]
Yes, putting all head-tags in one statements works. Thanks for your explanations.
