### ISSUE TITLE
Syntax Wiki: Second table in table section not highlighted

### ISSUE THREAD

**Issue by actuallymentor** [fletcher/MultiMarkdown#57]
Hello!

I'm not sure whether you intended the wiki to be read on Github or within an MMD reader. If Github was the target adding syntax highlighting tags might be a good idea. I can do a PR if you'd like.

<img width="762" alt="screen shot 2017-12-02 at 10 28 10" src="https://user-images.githubusercontent.com/9071382/33513965-b0711134-d74b-11e7-8d47-3e7c07596385.png">

**Comment by fletcher** [comment]
This repo is for the earliest version of MMD, back in the Perl days.

It has been deprecated for years.

[Here](https://github.com/fletcher/MultiMarkdown-6) is the current version
