### ISSUE TITLE
Free and Open source Editors for MultiMarkDown with Live preview?

### ISSUE THREAD

**Issue by Foadsf** [fletcher/MultiMarkdown#58]
As I have asked this question [here](https://www.reddit.com/r/writing/comments/b0ywcw/free_markdown_editors_with_live_preview_for/) in more details, I'm looking for Free and Open Source (FOSS) editors which are able to render MultiMarkDown, Specially the "[File Transclusion](https://fletcher.github.io/MultiMarkdown-5/transclusion.html)" feature. I have tried GhostWriter, vscode, Typora, Haroopad... recognize this syntax. Thanks for your help in advance. 

P.S. I also asked your Twitter account [here](https://twitter.com/fsfarimani/status/1106148370773692416).

**Comment by fletcher** [comment]
Responded via Twitter.  MultiMarkdown Composer is my editor.  It's available on macOS App Store, and contains many features that are not contained in any other editors.  But it's not open-source.

[https://multimarkdown.com/](https://multimarkdown.com/)

**Comment by Foadsf** [comment]
@fletcher Thanks for the response. It sad to see that there are no feasible FOSS solution for MultiMarkDown. Unfortunately I have to switch to AsciiDoc for the moment as it comes with the include functionality built-n supported by both vscode and atom editors.

**Comment by fletcher** [comment]
Yup. Sometimes when you want good software that takes a lot of somebody’s time to develop, you have to pay for it.... or build it yourself. Which has its own cost.
