### ISSUE TITLE
Wrong number used in LaTeX for figure and tables references

### ISSUE THREAD

**Issue by ghost** [fletcher/MultiMarkdown#6]
At times when referencing a LaTeX figure, using the MMD command `[](#ref_foo)`, will reference the wrong number. The problem appears to be that the `\label{}` code in `xhtml2latex.xslt` comes before the `\caption{}` code. To solve, I recommend moving the `\label{}` code to be inside the `\caption{}` code, such as `\caption{\label{ref_foo} Caption for the Figure}`.

**Comment by cumulusware** [comment]
Fixed in commit 2c7259500f0a8f87e09b535d3a0f8a0cdacf5520

**Comment by fletcher** [comment]
Done.
