### ISSUE TITLE
XHTML Footer:  ?

### ISSUE THREAD

**Issue by hornsong** [fletcher/MultiMarkdown#60]
To implement a script at the bottom of the html file a XHTML Footer: parameter is required.

**Comment by fletcher** [comment]
This version (2.0) has been deprecated for many years.  The current version is v6.  (Which has the functionality you desire.)

https://github.com/fletcher/MultiMarkdown-6

**Comment by hornsong** [comment]
Oke nice, so you didn’t  updated it  in your wiki?
I can only see XHTML Header:
But there is no XHTML Footer?

https://github.com/fletcher/MultiMarkdown/wiki/MultiMarkdown-Syntax-Guide

Kind regards,
Lydia

Van: Fletcher T. Penney
Verzonden: maandag 23 maart 2020 14:03
Aan: fletcher/MultiMarkdown
CC: hornsong; Author
Onderwerp: Re: [fletcher/MultiMarkdown] XHTML Footer: ? (#60)

This version (2.0) has been deprecated for many years. The current version is v6. (Which has the functionality you desire.)
https://github.com/fletcher/MultiMarkdown-6

**Comment by fletcher** [comment]
The entire project is deprecated (and has been for over 9 years at this point) -- the wiki was specifically for version 2 and is part of that project.

v6 has a link to the corresponding documentation:

<https://fletcher.github.io/MultiMarkdown-6/>

**Comment by hornsong** [comment]
Hi Fletcher T Penny,

You closed it to early. 

I tried it out, with the new version  6, but it does not work. 

Similar as I do with 
XHTM header:
I used a script at 
XHTML footer:

Like this:
……
XHTML header: <script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script
XHTML footer:  <script type="text/javascript"…..
……


But it doesn’t put the script at the bottom of a html file.
Instead it put it at the top of the html file, like this
<meta name="xhtmlfooter" content="&lt;script type=&quot;text/javascript&quot;&gt……..

When I edit the html file and put the script manually at the bottom of the html file, then  it works fine.

Could you solve this? That would be great.

Kind regards,
Lydia

Van: Fletcher T. Penney
Verzonden: maandag 23 maart 2020 14:03
Aan: fletcher/MultiMarkdown
CC: hornsong; Author
Onderwerp: Re: [fletcher/MultiMarkdown] XHTML Footer: ? (#60)

Closed #60.

**Comment by fletcher** [comment]
MultiMarkdown migrated from "xhtml" naming conventions to using "html" a long time ago (remember, MultiMarkdown v2 came out many years ago, before HTML 5, and was in development back when XHTML was a new-ish, "hot" thing, but treated somewhat differently than HTML.

Now MultiMarkdown focuses on HTML 5, and makes use of "htmlheader" and "htmlfooter" metadata naming for these fields.  "xhtmlheader" is still around as a deprecated variant, but "xhtmlfooter" will not be added without a really good reason.
