### ISSUE TITLE
MultiMarkdown: invalid option "--process-html"

### ISSUE THREAD

**Issue by alecjacobson** [fletcher/MultiMarkdown#61]
Using Multimarkdown 5.4 (and earlier I believe), I was able to mix markdown inside html tags using the `--process-html` flag to make sure this markdown gets processed. In version 6.0 I'm now getting this error:

    MultiMarkdown: invalid option "--process-html"

Is this flag gone? Is there another way to achieve the same effect?

**Comment by fletcher** [comment]
This repo is for MultiMarkdown version 2.  You found the correct place for discussion here:  <https://github.com/fletcher/MultiMarkdown-6/issues/98>
