### ISSUE TITLE
Bug: First line becomes metadata (mmd2XHTML)

### ISSUE THREAD

**Issue by brief** [fletcher/MultiMarkdown#7]
A minor bug. If there is no metadata, converting a markdown file to XHTML appends the first line of text to the `<meta name="Format" content="complete" />` tag and strips it from the body.

E.g.: a file containing `Hello World!` will be formatted as:

```
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <!-- Processed by MultiMarkdown -->
        <meta name="Format" content="complete
Hello World!" />
    </head>
<body>


</body>
</html>
```

**Comment by fletcher** [comment]
Not really a bug - it's the way metadata works, but I might be able to put in an exception for that one situation.

**Comment by fletcher** [comment]
Latest push to github adds a specific check for "format: complete" and doesn't automatically treat the next line as metadata.  Thanks for prompting me to do this (I should have done it long ago!)

**Comment by brief** [comment]
Terrific, thank you!
