### ISSUE TITLE
Beamer XSLT BibTex problems

### ISSUE THREAD

**Issue by sk2** [fletcher/MultiMarkdown#8]
Hi,
I am having problems with using the beamer xslt and Bibtex.
If I use "LaTeX XSLT: beamer ", I get the following error when running Bibtex:

```
This is BibTeX, Version 0.99c (Web2C 7.5.6)

I found no \bibdata command---while reading file scriv.aux

I found no \bibstyle command---while reading file scriv.aux
```

When I change the xslt to "LaTeX XSLT: article  "
I get no such problem.

I notice that the beamer xslt does not append the 

```
%   Bibliography
\bibliographystyle{\mybibliostyle}
\bibliocommand
```

Bit to the bottom of my document. I think it isn't being correctly matched in the XSLT, but I cannot work out exactly what the problem is.
Thanks!
Simon

**Comment by fletcher** [comment]
I just pushed an update that should fix this for you.  Please let me know if it worked. Thanks!

**Comment by sk2** [comment]
Hi, Unfortunately not. I get the same error.
Would you like me to simplify my source mmd file and make it available?
Thanks for your time,
Simon

**Comment by fletcher** [comment]
Sure - just email to me at owner@fletcherpenney.net and I'll take a look at it.

**Comment by fletcher** [comment]
This should be fixed now.  Thanks!

**Comment by sk2** [comment]
Yep all fixed, thanks :)
