### ISSUE TITLE
Citation documentation

### ISSUE THREAD

**Issue by brief** [fletcher/MultiMarkdown#9]
A suggested clarification for citations in the MultiMarkdown documentation. This:

```
You are not required to use a locator (e.g. p. 23), and there are
no special rules on what can be used as a locator if you choose
to use one.
```

To this:

```
You are not required to use a locator (e.g. p. 23), and there are
no special rules on what can be used as a locator if you choose
to use one. If you prefer to omit the locator, just use an empty
set of square brackets before the citation:

    This is a statement that should be attributed to its 
    source[][#Doe:2006].
```

**Comment by fletcher** [comment]
Done.

**Comment by wadoli** [comment]
The Syntax-Guide-Wiki (https://github.com/fletcher/MultiMarkdown/wiki/MultiMarkdown-Syntax-Guide) says

«Notice the inconsistency between references with and without locator. The empty square brackets have to be placed AFTER the reference, not before.»

and

«Notice that empty square brackets have to be placed AFTER the reference if you don't want to use a locator:»

This is incorrect, isn't it?

**Comment by fletcher** [comment]
Correct way to do citation is the same as all other markdown references - if only one piece of data is being used, it goes in the first set of brackets.  Second set of brackets is then optional.

MMD 2 and MMD 3 currently handle this slightly differently.  MMD 3, when finished, will be the "correct" way and then I will work on trying to modify MMD 2 to comply.
